fix: Firebase Functions Deploy error jsryudev/deploy-firebase-functions@v20.0.1 が 内部で Docker を使っていて、その Docker コンテナ内に pnpm が入っていないのが原因。
「ホスト側（GitHub Actions の通常ジョブ）」で lint や build を先に実行し、
.firebase.json の predeploy を除去する

```
Run jsryudev/deploy-firebase-functions@v20.0.1
  env:
    CI: true
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    FIREBASE_TOKEN: ***
    FIREBASE_PROJECT: ***
    FUNCTIONS_DIR: functions
/usr/bin/docker run --name a3308fddcb457ad487a83e3d65e5f0b4c6e_d26001 --label 598a33 --workdir /github/workspace --rm -e "CI" -e "PNPM_HOME" -e "FIREBASE_TOKEN" -e "FIREBASE_PROJECT" -e "FUNCTIONS_DIR" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/***/***":"/github/workspace" 598a33:08fddcb457ad487a83e3d65e5f0b4c6e
npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /github/home/.npm/_logs/2025-04-22T12_36_51_200Z-debug-0.log
⚠  Authenticating with `FIREBASE_TOKEN` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started

=== Deploying to '***'...

i  deploying functions
Running command: pnpm --prefix "$RESOURCE_DIR" run lint
/bin/sh: 1: pnpm: not found

Error: functions predeploy error: Command terminated with non-zero exit code 127
  ```